version: '3.9'

services:
  fiap_staging:
    image: fiap_app:staging
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "8081:8080"
    restart: unless-stopped

  fiap_production:
    image: fiap_app:production
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
    restart: unless-stopped
