version: '3.8'

services:
  fiap_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
