name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run Unit Tests
        run: dotnet test

      - name: Run BDD Tests with SpecFlow
        run: |
          echo "Running BDD tests with SpecFlow..."
          # Comando para rodar os testes SpecFlow (exemplo para .NET)
          dotnet build
          dotnet test --filter "TestCategory=BDD"  # Supondo que você tenha marcado seus testes BDD com a tag 'BDD'
        
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging..."
          # Comandos reais para deploy no ambiente de staging

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Comandos reais para deploy na produção
