name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código fonte
      - name: Checkout repository
        uses: actions/checkout@v2

      # Logar no Docker Hub usando os secrets configurados no GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: felipefzn
          password: felipe10092004

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t felipefzn/fiap_app:latest .

      # Enviar a imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push felipefzn/fiap_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout do código novamente
      - name: Checkout repository
        uses: actions/checkout@v2

      # Realizar deploy, aqui você pode adicionar seu processo de deploy
      # Exemplo de como fazer deploy para algum serviço, como o Azure, AWS, etc.
      - name: Deploy to Cloud (substitua isso com seu processo de deploy)
        run: |
          echo "Deploying the app to the cloud"
